esphome:
  name: aeroq
  name_add_mac_suffix: true
  friendly_name: Aeroq Air Monitor
  project:
    name: "neyra.aeroq"
    version: "1.0.0"
  includes:
    - src/aeroq_display.h
  platformio_options:
    lib_deps:
      - zinggjm/GxEPD2@^1.6.4
      - adafruit/Adafruit GFX Library@^1.12.3
      - adafruit/Adafruit BusIO@^1.17.4
    lib_ldf_mode: deep+

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: recommended

wifi:
  ap:
    # ssid: "Aeroq-Setup"
    # No password for open AP
captive_portal:
improv_serial:

logger:
api:
http_request:
  verify_ssl: false

ota:
  - platform: esphome
  - platform: http_request
    id: ota_http

update:
  - platform: http_request
    id: aeroq_fw_update
    name: "Aeroq Firmware"
    source: "https://enriqueneyra.github.io/Aeroq/manifest.json"
    update_interval: 24h

# Your PCB wiring (C3 strapping-pin warnings are expected; safe on your board)
i2c:
  sda: 8
  scl: 0
  scan: true

sensor:
  - platform: scd4x
    id: scd41
    co2:         { name: "CO2", id: co2, accuracy_decimals: 0 }
    temperature: { name: "Temp (SCD41)", id: t_scd, accuracy_decimals: 1 }
    humidity:    { name: "RH (SCD41)",   id: rh_scd, accuracy_decimals: 1 }
    update_interval: 10s

  - platform: sen5x
    pm_1_0:      { name: "PM1.0", id: pm1_0, accuracy_decimals: 1 }
    pm_2_5:      { name: "PM2.5", id: pm2_5, accuracy_decimals: 1 }
    pm_4_0:      { name: "PM4.0", id: pm4_0, accuracy_decimals: 1 }
    pm_10_0:     { name: "PM10",  id: pm10_0, accuracy_decimals: 1 }
    voc:         { name: "VOC Index", id: voc_index, accuracy_decimals: 0 }
    temperature: { name: "Temp (SEN54)", id: t_sen, accuracy_decimals: 1 }
    humidity:    { name: "RH (SEN54)",   id: rh_sen, accuracy_decimals: 1 }
    update_interval: 10s

interval:
  - interval: 5s
    then:
      - lambda: |-
          aeroq_display::tick_and_draw(
            (uint16_t) id(co2).state,
            id(t_scd).state, id(rh_scd).state,
            id(t_sen).state, id(rh_sen).state,
            id(pm1_0).state, id(pm2_5).state,
            id(pm4_0).state, id(pm10_0).state,
            id(voc_index).state
          );
